=== joomla/schemas/xsd/v3/language.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:include schemaLocation="common.xsd"/>

    <xs:element name="metafile">
        <xs:complexType>
            <xs:all>
                <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
                <xs:element name="tag" type="locales" minOccurs="0" maxOccurs="1"/>
                <xs:element name="author" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="authorEmail" type="validateEmail" minOccurs="0" maxOccurs="1"/>
                <xs:element name="authorUrl" type="xs:anyURI" minOccurs="0" maxOccurs="1"/>
                <xs:element name="copyright" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="license" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="version" type="versionType" minOccurs="1" maxOccurs="1"/>
                <xs:element name="creationDate" type="xs:string" minOccurs="0" maxOccurs="1"/>
                <xs:element name="description" type="xs:normalizedString" minOccurs="0" maxOccurs="1"/>
                
                <xs:element name="files" type="filesType" minOccurs="0" maxOccurs="1"/>
                <xs:element name="metadata" type="metadata" minOccurs="0" maxOccurs="1"/>
                <xs:element name="params" type="params" minOccurs="0" maxOccurs="1"/>
            </xs:all>
            <xs:attribute name="client" use="required" type="clientType"/>
            <xs:attribute name="version" use="required" type="versionType"/>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="metadata">
        <xs:all>
            <xs:element name="name" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="tag" type="xs:NCName" minOccurs="1" maxOccurs="1"/>
            <xs:element name="rtl" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="firstDay" type="xs:integer" minOccurs="0" maxOccurs="1"/>
            <xs:element name="weekEnd" type="weekEndType" minOccurs="0" maxOccurs="1"/>
            <xs:element name="locale" type="xs:string" minOccurs="1" maxOccurs="1"/>
            <xs:element name="winCodePage" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
            <xs:element name="backwardLang" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
            <xs:element name="pdfFontName" type="xs:NCName" minOccurs="0" maxOccurs="1"/>
        </xs:all>
    </xs:complexType>

    <xs:complexType name="params">
    </xs:complexType>

    <xs:simpleType name="weekEndType">
        <xs:annotation>
            <xs:documentation xml:lang="en">Validate weekEnd</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9],[0-9]"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== joomla/schemas/xsd/v3/language.xml
<?xml version="1.0" encoding="utf-8"?>
<metafile version="1.6" client="site" xsi:noNamespaceSchemaLocation="language.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<name>Examplish (Example)</name>
	<tag>en-US</tag>
	<version>1.6.0</version>
	<creationDate>2008-03-15</creationDate>
	<author>Joomla! Project</author>
	<authorEmail>admin@joomla.org</authorEmail>
	<authorUrl>www.joomla.org</authorUrl>
	<copyright>Copyright (C) 2005 - 2011 Open Source Matters. All rights reserved.</copyright>
	<license>http://www.gnu.org/licenses/gpl-2.0.html GNU/GPL</license>
	<description/>
	<metadata>
		<name>Examplish (Example)</name>
		<tag>xx-XX</tag>
		<rtl>0</rtl>
		<locale>xx_XX.utf8, xx_XX.UTF-8, xx_XX, xx, examplish, examplish-example</locale>
		<winCodePage>iso-8859-1</winCodePage>
		<backwardLang>examplish</backwardLang>
		<pdfFontName>freesans</pdfFontName>
	</metadata>
	<params></params>

</metafile>
